#!/bin/sh
# simple screenshot script

tmpfilename=sstmp.png
sspath=~/Obrazy/ss
dirname=$(date +%m-%Y)
randstr=$(head -c 5 /dev/urandom | base32)
timestamp=$(date +"%d %b %H:%M:%S") 

import /tmp/$tmpfilename
#scrot -s "$tmpfilename"
#mv $tmpfilename /tmp/$tmpfilename

mkdir -p $sspath/$dirname

filename=$(echo auto | dmenu -p "nazwa zrzutu ekranu:")

case $filename in
	"auto") filename="zrzut ekranu - $timestamp" ;;
	"") exit ;;
esac


xclip -selection clipboard -t image/png -i /tmp/$tmpfilename
mv /tmp/$tmpfilename $sspath/$dirname/"$filename.png"
