#!/bin/sh
if egrep -q '#.*youtube' /etc/hosts
then 
	echo blocking youtube.com
	doas sed -i '/^#.*youtube*/s/^#//' /etc/hosts
else
	echo youtube.com already blocked
	exit
fi

echo Kill firefox? [y/N]
read answer
case $answer in
	y|Y)
		pkill -f firefox
		;;
	*)
		echo exiting
esac
